### PR TITLE
Fix app crash if device has no bluetooth support

### PR DESCRIPTION
**Pull request by quincunx**
finish() does not exit app, it just closes the Activity. Therefore
app will continue and crash at pairedDevicesList().

### CODE REVIEW

**Comment by martinohanlon** [comment]
Thanks for the PR. Has this change been tested? I can test as I don't have a non bluetooth android device.

**Comment by martinohanlon** [comment]
Should be 

"I can't test"

**Comment by quincunx** [comment]
You can test it in the emulator, as there is no Bluetooth available. Without this change, the app will always crash. When you debug it, you will see that the processing of the code won't stop at finish(). Exit() is required in this case.

**Comment by martinohanlon** [comment]
Ok. Have you tested on a real device? I wanted to understand the risk of releasing the code, even though the current exit process for non bluetooth device is effectively untested.

**Comment by martinohanlon** [comment]
This change will wait until the next release of the app.

**Comment by martinohanlon** [comment]
Included in codeVersion 2 (1.1) of the app.

**Pull request closed without merging**
